name: my-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - basemap
  - ipympl
  - pandas
  - seaborn
  - boto3
  - json
  - jupyterlab-webrtc-docprovider
